[20.21.9] US129402 -- Fixed feedback lagging behind cell selection
Brightspace/d2l-rubric pull request #1054
Opened 2021-09-08 14:54 UTC by mpharoah-d2l

2021-09-08 16:20 UTC, semibran approved these changes
Yeah I can see how this'll conflict now. I think we converged on a bunch of similar solutions (keeping a copy of local criteria group selection state) but we went about it in different ways. I'm not sure how necessary it is to use `Map` here in general since the keys are just strings, but it might be a bit cleaner semantically so I'll defer to your judgment on that.

2021-09-08 16:20 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I'm partial towards keeping this out of the queueing logic but I had to redo all of that stuff anyways for the popout view so it might be a bit tough to merge. Another thing is that we can't base selection/deselection off assessed state alone since assessed state gets outdated by every request. That's another discussion though

2021-09-08 16:20 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			value: 0
where is versioning used?

2021-09-08 16:20 UTC, semibran commented on d2l-rubric-criteria-group.js
> +								<d2l-rubric-criterion-cell href="[[_getSelfLink(criterionCell)]]" token="[[token]]" cell-assessment="[[_lookupMap(criterionCell,cellAssessmentMap)]]" optimistic-update-dispatcher="[[_dispatch
seems like this is unused

2021-09-08 16:20 UTC, semibran commented on d2l-rubric-criterion-mobile.js
> +	_selectCellOptimistic: function(entity) {
I think the inline view already has a bunch of `selected`/`focused`/`hovered` stuff to avoid having to store optimistic updates separately. Is default feedback supposed to show up for hovered levels or just on selection?

2021-09-08 16:56 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			value: 0
The actual value is unused, but it's passed in as an unused parameter when we need a function to be recalculated

2021-09-08 16:57 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			value: 0
To clarify, changing an array or object (unless you change the reference itself) won't trigger an update in computed methods that depend on it, so you can get around that by passing in an unused version variable so the computation is re-run when the version is incremented

2021-09-08 16:58 UTC, mpharoah-d2l commented on d2l-rubric-criterion-mobile.js
> +	_selectCellOptimistic: function(entity) {
Just on selection. But it was previously relying on the actual entity being returned by the server and didn't have a local state.

2021-09-08 17:03 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			value: 0
got it, just polymer things

2021-09-08 17:11 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Yeah, it currently is a little buggy if you deselect a cell before the selection goes through. I don't know of a good way to fix this though since we don't have the unselect action available until the selection response comes back

2021-09-08 17:14 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Actually, because of the entityGetter being evaluated later, it might still work. Will just require an additional state to be storedd

2021-09-08 17:18 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Right so the way I figured out how to do it without an explicit deselect action is pretty simple, it just needs to cache the latest requested level href per criterion. If the user selects the latest requested level again then they've deselected it

2021-09-08 17:20 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I removed the entity getters and just used level hrefs since assessment entities get outdated on every selection. Hard to explain but the scoping stuff just adds an extra layer of complexity. Might have to run through the logic for that one more time to make sure we're not missing anything as a result of that though.

2021-09-08 18:13 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I got this working by checking the current optimistic state. It still works when sending the actual request to the server, because the entityGetter gets the latest state of the entity before running the action, so it gets the unselect action instead of the selection one, and everything syncs up

2021-09-08 18:51 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
It's difficult to explain but without caching requested state the assessment entity still gets outdated, which ultimately turns up a false positive for cell deselection. The test case I've been using is selecting a cell, moving to another cell, then reselecting the first one.

2021-09-08 19:01 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
It works fine in the popout view since it's only relying on local state for the optimistic logic. There seems to be a bug with the local state in the mobile view though

2021-09-08 19:03 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Oh, nevermind, I see what you mean

2021-09-08 19:07 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Though that seems like a bug in the promise queue- it _should_ get the updated assessment before each queued action, so it should work anyways, but someone the entity is in an old state I guess, which shouldn't happen.

2021-09-08 19:16 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Not necessarily, `queueChange` (now `queueCriterionCellAssessment`) only gets called once as soon as the user selects a cell. So any checks that you do directly inside that function outside of like callbacks and stuff are gonna use the assessment entity at that particular moment.

2021-09-08 19:20 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
That's true, but I don't rely on that anymore. Instead the entity is only used when evaluated in the promise queue, at which point it should be consistent with the state of all actions performed beforehand, so it's select action should now be selection again since the previous action unselected it, but for some reason this isn't happening, and I'm not sure why

2021-09-08 19:24 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
did you end up moving the optimistic selection checks? or do you mean you're not using them anymore

2021-09-08 19:29 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Setting the new optimistic state now only depends on the current assessment if there isn't an optimistic state yet (and since it never gets cleared, that means that this is the initial state when the rubric was loaded). All other times, it looks at the current optimistic state to determine the next state, so it correctly handled deselection regardless of what the current state validated by the server is.

At the same time, the way the promise queue works is that when it's a queued action's time to send, it uses `entityGetter` to refresh the state to what should be the last state confirmed by the server. Since it does this every step, it should always end up with the exact same state as the optimistic state unless an error occurs. But for some reason, that doesn't seem to be working and it's doing the wrong action in the case you described where you select another level then select the initial one again. It seems to think the initial one is still selected, but it shouldn't.

2021-09-08 19:36 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Oh, I think it's because `entityGetter` is getting replaced in the debouncer logic for some reason

2021-09-08 19:37 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Yeah, I think `_changesQueued` is trying to duplicate the work of the promise queue instead of letting the queue handle it, so it ends up with diverging states that cause undefined behaviour based on what the current state happens to be

2021-09-08 19:39 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Do we actually even still need the debouncer? With optimistic updates, it updates instantly anyways. Removing that would fix everything I think

2021-09-08 19:56 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Yep, looks like that fixes it. Removing the debouncer and relying on the optimistic update map instead completely fixes all synchronization issues 🎉 ...except the checkmark in the popout view still slightly lags behind for some reason.

2021-09-08 19:58 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I rewrote the queueing logic in my PR to handle a few more cases but I think we'll need more time + some kind of automated test mocking if we want complete case coverage.

It shouldn't be that difficult to get correct outputs without the debouncer so I'm fine with removing it at least just to get these hotfixes in. I agree the debouncer is less useful now that we have optimistic updates but I think there's still a use for it, since it dedupes requests -> shaves down save times significantly for keyboard users on slow connections. It's just a nice to have though and again it'll take a while to get it to work perfectly.

2021-09-08 20:00 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
There's a fix to the checkmark in my PR btw. It was passing in the assessment entity (old state) to determine whether or not to display the checkmark so I just refactored it into a `selected` boolean that uses the selection state (your optimistic update map) like everything else.

2021-09-08 20:08 UTC, semibran commented
as an aside/minor nit I think calling everything optimistic selections etc. is a bit backend-centric for naming whats essentially the local state of a frontend component. But we can just fix this during the lit refactor if you want

2021-09-08 20:23 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Yeah, you're right- removing the debouncer does potentially put more load on the server, especially for keyboard users; however removing it significantly simplifies the code and fixes desyncs without the need for extra complexity, plus it completely removes the need to make the "outside world" aware of the debouncer to prevent dialogs from being closed in that time, so I would rather proceed with removing it.

2021-09-08 20:24 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I have everything working now except that the initial state when you load the page in the mobile view is now partially incorrect, and it doesn't get synced with the new state if you open the popout dialog, make some changes, then close it and open back up the mobile view without reloading the page. I'm working on fixing that now

2021-09-08 20:32 UTC, semibran commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
I'll figure out how to merge in my aria-checked fixes once your stuff is ready to go

2021-09-08 20:38 UTC, mpharoah-d2l commented on d2l-rubric-criteria-group.js
> +			this._dispatcher.selectLevel(criterionHref, levelHref);
Cool. Sounds good

2021-09-09 14:08 UTC, semibran requested changes

2021-09-09 14:08 UTC, semibran commented on .eslintrc.json
> +	"Map": true
Mixing tabs and spaces
```suggestion
    "Set": true,
    "Map": true
```

2021-09-09 14:08 UTC, semibran commented on assessment-helpers/criterion-assessment.js
> +	isOptimisticlySelected(criterionAssessmentEntity, optimisticUpdateMap) {
```suggestion
	isOptimisticallySelected(criterionAssessmentEntity, optimisticUpdateMap) {
```

2021-09-09 14:08 UTC, semibran commented on d2l-rubric-criteria-group.js
> +		if (this.CriterionAssessmentHelper.isOptimisticlySelected(entity, this._optimisticSelections)) {
```suggestion
		if (this.CriterionAssessmentHelper.isOptimisticallySelected(entity, this._optimisticSelections)) {
```

2021-09-09 14:20 UTC, semibran approved these changes

2021-09-09 14:33 UTC, merged