DE46966 -- Fixed the inline rubric assessment view not updating after the popout view is closed
Brightspace/d2l-rubric pull request #1580
Opened 2022-02-04 18:19 UTC by mpharoah-d2l

https://rally1.rallydev.com/#/57732444928d/dashboard?detail=%2Fdefect%2F623239637233

2022-02-04 18:21 UTC, mpharoah-d2l commented on src/components/rubric-levels-mobile.js
> +				this.ouDispatcher.rollback(this.criterionHref);
This syncs the state back up with the entity once all pending requests are completed, so it can get updates from the popout view again

2022-02-04 21:45 UTC, devpow112 approved these changes
Looks good to me :tada:

2022-02-07 13:55 UTC, imcdonald-d2l requested changes

2022-02-07 13:55 UTC, imcdonald-d2l commented on src/components/rubric-levels-mobile.js
> +	deselect() {
`overall-score-mobile` expects a callback function here to update overall score on deselect. I added this since overall score wasn't updating properly on deselect. If this is no longer needed than it should be removed from overall-score-mobile as well. But should be tested that deselecting overall-score updates everything as expected before removing this callback.

2022-02-07 14:25 UTC, mpharoah-d2l commented on src/components/rubric-levels-mobile.js
> +	deselect() {
I think that should happen automatically because of the link hreaders in the siren response, but I'll check it out

2022-02-07 14:36 UTC, imcdonald-d2l commented on src/components/rubric-levels-mobile.js
> +	deselect() {
Yeah, if it's working without the callback now that's great. We can just remove the callback in `overall-score-mobile` so it isn't passing a callback unnecessarily if it is working.

2022-02-07 18:05 UTC, imcdonald-d2l approved these changes

2022-02-07 18:09 UTC, devpow112 approved these changes

2022-02-07 18:46 UTC, merged