Standards now have text to convey what criterion they belong to
Brightspace/d2l-rubric pull request #700
Opened 2021-02-08 14:39 UTC by MitchelPaulin

Added an aria-label, screen reader will not describe what standards are aligned to what criterion, tested on NVDA

2021-02-08 15:07 UTC, rgoessl requested changes

2021-02-08 15:07 UTC, rgoessl commented on d2l-rubric-alignments-indicator.js
> +			return "Standards aligned to " + criterionName;
Must use a lang term for this

2021-02-08 15:08 UTC, MitchelPaulin commented on d2l-rubric-alignments-indicator.js
> +			return "Standards aligned to " + criterionName;
I asked @fionaffzhang  and she said we don't need to add lang terms for screen reader only text.

2021-02-08 15:13 UTC, fionaffzhang commented on d2l-rubric-alignments-indicator.js
> +			return "Standards aligned to " + criterionName;
I thought we were discussing language translation? I could be wrong. 
Also the word "standard" is custom-specified so I suppose that needs to be a lang term

2021-02-08 15:14 UTC, MitchelPaulin commented on d2l-rubric-alignments-indicator.js
> +			return "Standards aligned to " + criterionName;
Sounds good, I'll add a lang term

2021-02-08 19:49 UTC, rgoessl requested changes

2021-02-08 19:49 UTC, rgoessl commented on lang/en.json
> +	"standardsAligned": "Standards aligned to {name}",
You need to use a select like this to get the configured outcomes term: https://github.com/Brightspace/d2l-outcomes-overall-achievement/blob/master/lang/en.js#L36

2021-02-08 20:20 UTC, MitchelPaulin commented on lang/en.json
> +	"standardsAligned": "Standards aligned to {name}",
I'm not sure what you mean, what word here needs to be configured?

2021-02-08 20:23 UTC, rgoessl commented on lang/en.json
> +	"standardsAligned": "Standards aligned to {name}",
`Standards` is a configurable term. It could be Outcomes, Objectives, Expectations... based on what client selects

2021-02-08 22:10 UTC, rgoessl requested changes

2021-02-08 22:10 UTC, rgoessl commented on lang/en.json
> +	"standardsAligned": "{outcome, select, competencies {competencies} expectations {expectations} objectives {objectives} outcomes {outcomes} standards {standards} other {standards}} aligned to {name}"
```suggestion
	"standardsAligned": "{outcome, select, competencies {Competencies} expectations {Expectations} objectives {Objectives} outcomes {Outcomes} standards {Standards} other {Standards}} aligned to {name}",
```

These should be capitalized (will need to re-run lang scripts)

2021-02-08 22:10 UTC, rgoessl commented on d2l-rubric-alignments-indicator.js
> +			return this.localize('standardsAligned', 'outcome', this.outcomesTitleText, 'name', criterionName);
I'm not sure if `outcomesTitleText` will give the expected value here. It's value comes from C# here https://search.d2l.dev/xref/lms/platformTools/rubrics/D2L.PlatformTools.Rubrics/Views/Default/RubricRenderer.cs?r=d9c7c68a#67 which I think is meant to be human readable (possibly already translated) version of the outcome term; whereas the `select` statement in the lang file expects it to exactly match one of the enum values from here: https://search.d2l.dev/xref/lms/le/lo/D2L.LE.LO/Web/Desktop/Controls/OutcomesMasteryViewTableRenderer.cs?r=88059323#58

Unfortunately you might have to add a new attribute to the rubric component, similar to the example above, to get it to work.

2021-02-09 15:36 UTC, rgoessl approved these changes

2021-02-09 15:39 UTC, devpow112 approved these changes
Feel free to ignore the language checker failures they are all false positives.

2021-02-09 15:45 UTC, merged