Rzhou/us115651 notify users of rubric structure
Brightspace/d2l-rubric pull request #716
Opened 2021-02-17 01:15 UTC by rebeccazhou0727

After talking to Fiona, we decided that if there is only 1 criteria group, this information is only displayed in reading mode. If there is more than 1 criteria group in a rubric, we would then give the rubric structure information again when the keyboard is focused on the criteria group name input text field.

Rally Ticket: https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F385560857244

2021-02-17 16:00 UTC, MitchelPaulin approved these changes

2021-02-17 16:27 UTC, Callum-Mitchell submitted a review, later dismissed

2021-02-17 17:56 UTC, rgoessl commented on editor/d2l-rubric-criteria-group-editor.js
> +					level-Count="{{levelCount}}"
```suggestion
					level-count="{{levelCount}}"
```

2021-02-17 18:00 UTC, rgoessl requested changes

2021-02-17 18:00 UTC, rgoessl commented on editor/d2l-rubric-criteria-group-editor.js
> +		levelCount: {
I think these can be private props (`_` prefix) and do not need `notify: true` as they are not used externally

2021-02-17 18:20 UTC, devpow112 commented
@rebeccazhou0727 you'll want to merge master to pickup the switch to GitHub Actions changes

2021-02-19 21:24 UTC, MitchelPaulin approved these changes

2021-02-23 14:48 UTC, rgoessl approved these changes

2021-02-23 14:50 UTC, merged