Rzhou/us124158 rubric criterion action menu
Brightspace/d2l-rubric pull request #735
Opened 2021-03-01 20:28 UTC by rebeccazhou0727

The Action menu should only appear when the `rubrics-criterion-action` feature flag is turned on while the remove trash-can icon will be hidden. We would need to reformat d2l-rubric-criterion-editor (specifically `gutter-right`) once we decide to remove this functionality permanently.

Expected Behavior: 

- Keyboard focus should be directly given to the input text area of the copied criterion
- Action menu being hidden when the  `rubrics-criterion-action`  is turned off or the criterion cannot be copied nor deleted

Added lang terms

- actionsforCriterion
- copiedCriterionLoading
- copyCriterion
- copyRow
- criterionCopied
- deleteCriterion
- deleteRow

Rally Ticket:
https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F484021014724

2021-03-01 21:21 UTC, MitchelPaulin commented on editor/d2l-rubric-criterion-editor.js
> +		rubricsCriterionAction: {
What does this variable represent?

2021-03-02 21:26 UTC, Callum-Mitchell reviewed
Nice work! Just one thing to check - see comment.

2021-03-02 21:26 UTC, Callum-Mitchell commented on editor/d2l-rubric-criterion-editor.js
> +			this.logCriterionCopiedAction(`criterionCopiedSatrted-${uuid}`, `criterionCopiedEnd=${uuid}`);
`criterionCopiedSatrted-${uuid}` - typo?

2021-03-02 21:52 UTC, rgoessl requested changes

2021-03-02 21:52 UTC, rgoessl commented on editor/d2l-rubric-criterion-editor.js
> +			setTimeout(function() {
What is this timeout for? Does the UI take a while to render after this succeeds?

2021-03-02 21:52 UTC, rgoessl commented on editor/d2l-rubric-criterion-editor.js
> +			this.dispatchEvent(new CustomEvent('d2l-rubric-criterion-copied', {
Is this event used?

2021-03-02 21:52 UTC, rgoessl commented on editor/d2l-rubric-criteria-groups-editor.js
> +		rubricsCriterionAction: Boolean,
I'm assuming this defaults to `value: false`?

2021-03-02 23:23 UTC, rebeccazhou0727 commented on editor/d2l-rubric-criterion-editor.js
> +			setTimeout(function() {
The `setTimeout `was in the `_handleAddCriterion `function so I thought the behaviour may be similar for copy

2021-03-02 23:24 UTC, rebeccazhou0727 commented on editor/d2l-rubric-criterion-editor.js
> +			this.dispatchEvent(new CustomEvent('d2l-rubric-criterion-copied', {
The event is not used anymore but similar events are created for d2l-rubric-criterion-deleted and d2l-rubric-criterion-added and they are not used anywhere in this repository. Should I just delete them?

2021-03-03 14:13 UTC, rgoessl commented on editor/d2l-rubric-criterion-editor.js
> +			this.dispatchEvent(new CustomEvent('d2l-rubric-criterion-copied', {
It doesn't look like any of them are used. Should be safe to delete

2021-03-03 15:48 UTC, rgoessl commented on editor/d2l-rubric-criterion-editor.js
> +			setTimeout(function() {
It's probably fine then

2021-03-03 15:49 UTC, rgoessl approved these changes

2021-03-03 15:50 UTC, merged